
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Aug 26 11:20:58 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 24;
  public static final int INCREMENT = 40;
  public static final int CONST = 7;
  public static final int ASSIGNMENT = 39;
  public static final int NOT_EQUALS_TO = 32;
  public static final int CONTINUE = 17;
  public static final int NUM_CONST = 23;
  public static final int DECREMENT = 41;
  public static final int GREATER_THAN = 33;
  public static final int SEMICOLON = 42;
  public static final int L_BRACES = 50;
  public static final int RECORD = 21;
  public static final int L_BRACKETS = 48;
  public static final int LESS_OR_EQUAL = 36;
  public static final int COMMA = 44;
  public static final int L_PARENTHESES = 46;
  public static final int CLASS = 4;
  public static final int SUBTRACTION = 27;
  public static final int IF = 8;
  public static final int THIS = 18;
  public static final int DOT = 45;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int EQUALS_TO = 31;
  public static final int LOGICAL_OR = 38;
  public static final int SUPER = 19;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MODULO = 30;
  public static final int R_BRACKETS = 49;
  public static final int R_PARENTHESES = 47;
  public static final int BREAK = 3;
  public static final int IDENT = 22;
  public static final int VOID = 15;
  public static final int COLON = 43;
  public static final int ELSE = 6;
  public static final int ENUM = 5;
  public static final int READ = 13;
  public static final int GOTO = 20;
  public static final int WHILE = 10;
  public static final int LOGICAL_AND = 37;
  public static final int ADDITION = 26;
  public static final int R_BRACES = 51;
  public static final int EXTENDS = 16;
  public static final int BOOL_CONST = 25;
  public static final int GRT_OR_EQUAL = 34;
  public static final int DIVISION = 29;
  public static final int LESS_THAN = 35;
  public static final int MULTIPLICATION = 28;
  public static final int PRINT = 12;
  public static final int DO = 9;
}

