
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
	/* terminals */
	
	// Keywords
	public static final int PROGRAM 		= 1;
	public static final int BREAK 			= 2;
	public static final int CLASS 			= 3;
	public static final int ENUM 			= 4;
	public static final int ELSE 			= 5;
	public static final int CONST 			= 6;
	public static final int IF 				= 7;
	public static final int DO 				= 8;
	public static final int WHILE 			= 9;
	public static final int NEW 			= 10;
	public static final int PRINT 			= 11;
	public static final int READ 			= 12;
	public static final int RETURN 			= 13;
	public static final int VOID 			= 14;
	public static final int EXTENDS 		= 15;
	public static final int CONTINUE 		= 16;
	public static final int THIS 			= 17;
	public static final int SUPER 			= 18;
	public static final int GOTO 			= 19;
	public static final int RECORD 			= 20;
	
	// Identifiers
	public static final int IDENTIFIER 		= 21;
	
	// Constants 
	public static final int NUM_CONST 		= 22;
	public static final int CHAR_CONST 		= 23;
	public static final int BOOL_CONST 		= 24;
	
	// Operators
	public static final int ADDITION 		= 25;
	public static final int SUBTRACTION 	= 26;
	public static final int MULTIPLICATION 	= 27;
	public static final int DIVISION 		= 28;
	public static final int MODULO 			= 29;
	public static final int EQUALS_TO 		= 30;
	public static final int NOT_EQUALS_TO 	= 31;
	public static final int GREATER_THAN 	= 32;
	public static final int GRT_OR_EQUAL 	= 33;
	public static final int LESS_THAN 		= 34;
	public static final int LESS_OR_EQUAL 	= 35;
	public static final int LOGICAL_AND 	= 36;
	public static final int LOGICAL_OR 		= 37;
	public static final int ASSIGNMENT 		= 38;
	public static final int INCREMENT 		= 39;
	public static final int DECREMENT 		= 40;
	public static final int SEMICOLON 		= 41;
	public static final int COLON 			= 42;
	public static final int COMMA 			= 43;
	public static final int DOT 			= 44;
	public static final int L_PARENTHESES 	= 45;
	public static final int R_PARENTHESES 	= 46;
	public static final int L_BRACKETS 		= 47;
	public static final int R_BRACKETS 		= 48;	
	public static final int L_BRACES 		= 49;
	public static final int R_BRACES 		= 50;
	
	// EOF
	public static final int EOF 			= 51;
}

